on:
  push:
    tags:
      - 'v*'

name: Create and upload Release of GitLab Runner Auth

jobs:
  build:
    name: Create Release
    runs-on: centos-7
    env:
      RPM_BUILD: $HOME/rpmbuild
      SPECS: $RPM_BUILD/SPECS
      RPMS: $RPM_BUILD/RPMS
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package
        run: |
          yum install -y rpmdevtools python3
          rpmdev-setuptree
          cp gitlab-runner-auth.spec $SPECS
          cd $SPECS
          spectool -g -R gitlab-runner-auth.spec
          rpmbuild -ba gitlab-runner-auth.spec
          RPM=$(find $RPMS -name *.rpm | grep -v "debuginfo")
          echo '::set-env name=RPM::$RPM'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $RPM
          asset_name: gitlab-runner-auth.rpm
          asset_content_type: application/zip
